version: '3'
services:
  web:
    image: dignz/ss-mailhog:latest
    working_dir: /var/www
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_eti
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${MYSQL_HOST}
    restart: always
    depends_on:
      - database
  database:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
  mailhog:
    image: mailhog/mailhog
    expose:
      - "8025"
    ports:
      - 8025:8025

volumes:
  db-data:
