
export const LOAD_CUSTOMER_LIST = 'ADM/LOAD_CUSTOMER_LIST';
export const LOAD_CUSTOMER_DETAIL = 'ADM/LOAD_CUSTOMER_DETAIL';
export const UPDATE_CUSTOMER_DETAIL = 'ADM/UPDATE_CUSTOMER_DETAIL';
export const DELETE_CUSTOMER_RECORD = 'ADM/DELETE_CUSTOMER_RECORD';
