export const SET_STUDENTS_LIST2STATE = 'ADM/SET_STUDENTS_LIST2STATE';
export const SET_STUDENT_DETAIL2STATE = 'ADM/SET_STUDENT_DETAIL2STATE';

export const PUT_STUDENT_DETAIL2STATE = 'ADM/PUT_STUDENT_DETAIL2STATE';

// Admin Remote API
export const GET_STUDENTS_LIST = 'ADM/GET_STUDENTS_LIST ';
export const GET_STUDENT_DETAILS_BY_ID = 'ADM/GET_STUDENTS_DETAILS_BY_ID';
export const UPDATE_STUDENT_DETAILS = 'ADM/UPDATE_STUDENTS_DETAILS';
export const DELETE_STUDENTS_LIST = 'ADM/DELETE_STUDENTS_LIST';
export const DELETE_STUDENT_BY_ID = 'ADM/DELETE_STUDENT_BY_ID';
export const UPDATE_STUDENT_STATUS = 'ADM/UPDATE_STUDENT_STATUS';

export const CREATE_STUDENT = 'ADM/CREATE_STUDENT';

