export const SET_CUSTOMERS_LIST2STATE = 'ADM/SET_CUSTOMERS_LIST2STATE';
export const SET_CUSTOMER_DETAIL2STATE = 'ADM/SET_CUSTOMER_DETAIL2STATE';

// Admin Remote API
export const GET_CUSTOMERS_LIST = 'ADM/GET_CUSTOMERS_LIST ';
export const GET_CUSTOMER_DETAILS_BY_ID = 'ADM/GET_CUSTOMERS_DETAILS_BY_ID';
export const UPDATE_CUSTOMER_DETAILS = 'ADM/UPDATE_CUSTOMERS_DETAILS';
export const DELETE_CUSTOMERS_LIST = 'ADM/DELETE_CUSTOMERS_LIST';
export const DELETE_CUSTOMER_BY_ID = 'ADM/DELETE_CUSTOMER_BY_ID';
export const UPDATE_CUSTOMER_STATUS = 'ADM/UPDATE_CUSTOMER_STATUS';
export const UPDATE_CUSTOMERS_STATUS = 'ADM/UPDATE_CUSTOMERS_STATUS';
